name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup Rust
      run: rustup target add riscv64gc-unknown-none-elf &&
           cargo install cargo-binutils --vers ~0.2 &&
           rustup component add llvm-tools-preview &&
           rustup component add rust-src
    - name: Build User & Lib
      run: cd user && make
    - name: Build Integration
      run: cd os && make
